XCode support, NATIVEWORD

diff --git a/distr/bin/linux/b2fj-go-linux b/distr/bin/linux/b2fj-go-linux
--- a/distr/bin/linux/b2fj-go-linux
+++ b/distr/bin/linux/b2fj-go-linux
@@ -1,16 +1,14 @@
 #!/bin/bash
+set -e
 
-exit_on_error() {
-    exit_code=$1
-    last_command=${@:2}
-    if [ $exit_code -ne 0 ]; then
-        >&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
-        exit $exit_code
-    fi
+abort()
+{
+    echo >&2 '
+*** ABORTED ***
+'
+    echo "An error occurred. Exiting..." >&2
+    exit 1
 }
-
-# enable !! command completion
-set -o history -o histexpand
 
 echo
 echo ===== b2fj .class to C =====
@@ -25,15 +23,13 @@ CURRENT_DIR=`pwd`
 echo "  b2fJ Home: $B2FJ_HOME"
 
 b2fj-compiler $1.java
-exit_on_error $? !!
 b2fj-linker $1
-exit_on_error $? !!
 b2fj-native-linux
-exit_on_error $? !!
 mv b2fj $1
-exit_on_error $? !!
 ./$1
-exit_on_error $? !!
 
-echo ============================
-echo DONE.
+trap : 0
+
+echo >&2 '
+*** DONE *** 
+'
